package com.example.lavugio_mobile.ui.admin;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.lifecycle.ViewModel;
import androidx.lifecycle.ViewModelProvider;

import com.example.lavugio_mobile.R;
import com.example.lavugio_mobile.data.model.user.DriverRegistrationData;
import com.example.lavugio_mobile.models.user.DriverRegistrationDTO;
import com.example.lavugio_mobile.ui.dialog.ErrorDialogFragment;
import com.example.lavugio_mobile.ui.dialog.SuccessDialogFragment;
import com.example.lavugio_mobile.viewmodel.admin.RegisterDriverViewModel;

public class RegisterDriverFragment extends Fragment {
    private DriverRegistrationData registrationData;

    private RegisterDriverViewModel viewModel;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_register_driver, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        registrationData = new DriverRegistrationData();

        viewModel = new ViewModelProvider(this).get(RegisterDriverViewModel.class);

        showDriverInformation();
    }

    public void showDriverInformation() {
        replaceChildFragment(RegisterDriverUserFragment.newInstance(registrationData));
    }

    public void showVehicleInformation() {
        replaceChildFragment(RegisterDriverVehicleFragment.newInstance(registrationData));
    }

    private void replaceChildFragment(Fragment fragment) {
        getChildFragmentManager()
                .beginTransaction()
                .replace(R.id.childFragmentContainer, fragment)
                .commit();
    }

    public void setRegistrationData(DriverRegistrationData data) {
        this.registrationData = data;
    }

    public void finishRegistration() {
        androidx.lifecycle.LiveData<Boolean> emailCheckLiveData = viewModel.fetchSameEmail(registrationData.getEmail());
        emailCheckLiveData.observe(getViewLifecycleOwner(), new androidx.lifecycle.Observer<Boolean>() {
            @Override
            public void onChanged(Boolean foundSameEmail) {
                emailCheckLiveData.removeObserver(this);
                
                if (foundSameEmail != null && foundSameEmail) {
                    ErrorDialogFragment.newInstance("Error", "User with this email already exists.")
                            .show(getActivity().getSupportFragmentManager(), "error_dialog");
                } else {
                    DriverRegistrationDTO dto = mapToDTO();
                    androidx.lifecycle.LiveData<String> registerLiveData = viewModel.registerDriver(dto);
                    registerLiveData.observe(getViewLifecycleOwner(), new androidx.lifecycle.Observer<String>() {
                        @Override
                        public void onChanged(String errorMessage) {
                            registerLiveData.removeObserver(this);
                            
                            if (errorMessage == null) {
                                SuccessDialogFragment.newInstance(
                                        "Success",
                                        "Driver registered successfully!"
                                ).show(getParentFragmentManager(), "success_dialog");

                                // Go back to previous screen after delay
                                new android.os.Handler().postDelayed(() -> {
                                    getParentFragmentManager().popBackStack();
                                }, 2000);
                            } else {
                                ErrorDialogFragment.newInstance("Error", errorMessage)
                                        .show(getActivity().getSupportFragmentManager(), "error_dialog");
                            }
                        }
                    });
                }
            }
        });
    }

    public DriverRegistrationDTO mapToDTO() {
        DriverRegistrationDTO dto = new DriverRegistrationDTO();
        dto.setEmail(registrationData.getEmail());
        dto.setPassword(""); // Password will be generated by backend
        dto.setName(registrationData.getName());
        dto.setLastName(registrationData.getSurname());
        dto.setPhoneNumber(registrationData.getPhone());
        dto.setAddress(registrationData.getAddress());
        dto.setVehicleMake(registrationData.getVehicleMake());
        dto.setVehicleModel(registrationData.getVehicleModel());
        dto.setLicensePlate(registrationData.getLicensePlate());
        dto.setVehicleColor(registrationData.getVehicleColor());
        dto.setVehicleType(registrationData.getVehicleType().toUpperCase());
        dto.setPassangerSeats(registrationData.getSeats());
        dto.setPetFriendly(registrationData.isPetFriendly());
        dto.setBabyFriendly(registrationData.isBabyFriendly());
        return dto;
    }
}
